#!/data/data/com.termux/files/usr/bin/bash

_dalvikvm=/data/data/com.termux/files/usr/bin/dalvikvm
_tmpdir=/data/data/com.termux/files/usr/tmp
_classpath=${PWD}/bin/textr.jar
_main_class=amsitlab.textr.App

unset LD_LIBRARY_PATH LD_PRELOAD
exec $_dalvikvm \
	-Djava.io.tmpdir=$_tmpdir \
	-cp $_classpath \
	$_main_class "$@"

unset _dalvikvm _tmpdir _classpath _main_class
